nonprod: &nonprod
  adapter:  postgresql 
  encoding: unicode/
  pool:     <%= ENV['DB_CONCURRENCY'] || 10 %>
  timeout:  5000

development:
  <<: *nonprod
  database: <%= ENV['DB_NAME'] || 'ict_dashboard_development' %>
  host:     <%= ENV['DB_HOST'] || '127.0.0.1' %>
  username: <%= ENV['DB_USER_NAME'] %>
  password: <%= ENV['DB_PWD'] || '' %>

# https://circleci.com/docs/environment#databases
# Both postgresql and mysql are set up to use the ubuntu user, have a database called circle_test available, and don't require any password.
test:
  <<: *nonprod
  database: <%= ENV['DB_NAME_TEST'] || 'ict_dashboard_test' %><%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5

staging:
  <<: *nonprod
  url: <%= ENV['DATABASE_URL'] %>

cloudfoundry:
  <<: *nonprod
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV['DB_CONCURRENCY'] || 20 %>
  timeout:  5000
